// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-llF3ObGIXZl46rsfpUNWVvJccTlHg8',
    appId: '1:1027565913417:web:dc5e35368d5566c2410698',
    messagingSenderId: '1027565913417',
    projectId: 'gapsfootball-629d1',
    authDomain: 'gapsfootball-629d1.firebaseapp.com',
    storageBucket: 'gapsfootball-629d1.firebasestorage.app',
    measurementId: 'G-E2CGFK4BTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHz-6iwW5s8ZtI8RVN93zB4dBCguDP8w',
    appId: '1:1027565913417:android:ce5e9ef9f0e0470e410698',
    messagingSenderId: '1027565913417',
    projectId: 'gapsfootball-629d1',
    storageBucket: 'gapsfootball-629d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJdcywPyKPrrwYDilWild8RVsy_A2Bcw',
    appId: '1:1027565913417:ios:52ca3d121c88d1c4410698',
    messagingSenderId: '1027565913417',
    projectId: 'gapsfootball-629d1',
    storageBucket: 'gapsfootball-629d1.firebasestorage.app',
    iosBundleId: 'com.example.gapsFootballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJdcywPyKPrrwYDilWild8RVsy_A2Bcw',
    appId: '1:1027565913417:ios:52ca3d121c88d1c4410698',
    messagingSenderId: '1027565913417',
    projectId: 'gapsfootball-629d1',
    storageBucket: 'gapsfootball-629d1.firebasestorage.app',
    iosBundleId: 'com.example.gapsFootballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo-llF3ObGIXZl46rsfpUNWVvJccTlHg8',
    appId: '1:1027565913417:web:edab1d2f60081ac9410698',
    messagingSenderId: '1027565913417',
    projectId: 'gapsfootball-629d1',
    authDomain: 'gapsfootball-629d1.firebaseapp.com',
    storageBucket: 'gapsfootball-629d1.firebasestorage.app',
    measurementId: 'G-T8LEG21WL0',
  );
}
